apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - image: "jenkins/inbound-agent:4.10-3"
    name: "jnlp"
    resources:
      limits: {}
      requests:
        memory: "256Mi"
        cpu: "100m"
  - command:
    - "cat"
    image: "107126629234.dkr.ecr.ap-southeast-1.amazonaws.com/java-node:11-jre-fermium"
    imagePullPolicy: "IfNotPresent"
    name: "node"
    resources:
      limits: {}
      requests: 
        cpu: 1000m
        memory: 2048Mi
    tty: true
  volumes:
  - name: "volume-0"
    secret:
      secretName: "aws-cli"
  - configMap:
      name: "docker-config"
    name: "volume-1"
  restartPolicy: "Never"
  nodeSelector:
    evermos.com/serviceClass: t3a-large-jenkins
